version: 1.0.1

user:
  name: 白云苍狗
  email: admin@imalun.com
  domain: https://www.imalun.com
  avatar: https://www.imalun.com/images/avatar.jpg
  title: 一觉游仙好梦，任它竹冷松寒。轩辕事，古今谈，风流河山。沉醉负白首，舒怀成大观。醒，亦在人间；梦，亦在人间
  desc: 醒，亦在人间；梦，亦在人间。
  birthDay: 11/19/2019 17:00:00 #计时开始时间
  resicence: Mars
  city: WuHan
  age: 18

favicon:
  visibilitychange: true
  hidden: /img/failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！

# 头部菜单
top_bars:
    - title: 首页
      url: /
    - title: 归档
      url: /archives/
    - title: 友链
      url: /links/
    - title: 树洞
      url: /comment/
    - title: 关于
      url: /about/
    - title: 虫洞
      url: https://foreverblog.cn/go.html
      noswup: true

# banner 配置信息
banner:
  index:
    type: img
    bgurl: https://pic1.zhimg.com/v2-b3c2c6745b9421a13a3c4706b19223b3_r.jpg?source=1940ef5c
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!
  archive:
    type: img
    bgurl: https://w.wallhaven.cc/full/j5/wallhaven-j5we85.jpg
    bannerTitle: 云间连下榻，<br>天上接行杯。
    bannerText: The article archive
  links:
    type: img
    bgurl: https://images.unsplash.com/photo-1563718428108-a2420c356c5c
    bannerTitle: 莫愁前路无知己，<br>天下谁人不识君。
    bannerText: A link to a friend's website
  comment:
    type: img
    bgurl: https://images.unsplash.com/photo-1621266309424-52f5a2e6d7f6
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: The magic tree hole
  about:
    type: img
    bgurl: https://images.unsplash.com/photo-1637118560941-b2363dcd8a8e?crop=entropy&cs=srgb&fm=jpg&ixid=Mnw4OTgyNHwwfDF8c2VhcmNofDE0fHwlRTYlOTclQTUlRTUlODclQkF8ZW58MHx8fHwxNjQ5NjcwODgz&ixlib=rb-1.2.1&q=85
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: About me

# 开启 Service Worker
sw: true

# rss 地址
rss: atom.xml

