version: 1.0.0

user:
  name: 白云苍狗
  email: admin@imalun.com
  domain: https://www.imalun.com
  avatar: https://www.imalun.com/images/avatar.jpg
  title: 一觉游仙好梦，任它竹冷松寒。轩辕事，古今谈，风流河山。沉醉负白首，舒怀成大观。醒，亦在人间；梦，亦在人间
  desc: 醒，亦在人间；梦，亦在人间。
  birthDay: 11/19/2019 17:00:00 #计时开始时间
  resicence: wuhan
  city: WuHan
  age: 18

favicon:
  visibilitychange: true
  hidden: /img/failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！

# 头部菜单
top_bars:
    - title: 首页
      url: /
    - title: 归档
      url: /archives/
    - title: 友链
      url: /links/
    - title: 树洞
      url: /comment/
    - title: 关于
      url: /about/
    - title: 虫洞
      url: https://foreverblog.cn/go.html
      noswup: true

# 开启 Service Worker
sw: true

# rss 地址
rss: atom.xml

