version: 1.0.3

user:
  name: 白云苍狗
  domain: https://www.imalun.com
  avatar: https://www.imalun.com/images/avatar.jpg
  title: 一觉游仙好梦，任它竹冷松寒。轩辕事，古今谈，风流河山。沉醉负白首，舒怀成大观。醒，亦在人间；梦，亦在人间
  desc: 醒，亦在人间；梦，亦在人间。

favicon:
  visibilitychange: true
  narmal: /images/favicon.png
  hidden: /images/failure.png
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

post_wordcount:
  wordcount: true # 单篇 字数统计
  min2read: true # 单篇 阅读时长

#开启 Service Worker
sw: true

#开启文章目录
isToc: true
#
canonical: true

cdn:
  css: 
    - //at.alicdn.com/t/font_1518765_5jbj7btfht2.css
  js:
    - //cdn.jsdelivr.net/npm/nprogress@0.2.0/nprogress.min.js
    - //cdn.jsdelivr.net/npm/jquery/dist/jquery.min.js
    - //cdn.jsdelivr.net/npm/jquery-pjax@2.0.1/jquery.pjax.min.js
    - //at.alicdn.com/t/font_1518765_5jbj7btfht2.js
    - //imgcache.qq.com/qcloud/tcbjs/1.6.0/tcb.js
    - //cdn.jsdelivr.net/npm/medium-zoom@1.0.6/dist/medium-zoom.min.js

menu:
  nav:
    - title: 白云苍狗
      url: /
    - title: ARCHIVES
      url: /archives
    - title: LINKS
      url: /links
    - title: COMMENTS
      url: /comment
    - title: ABOUT
      url: /about

rss: atom.xml