# 用户信息
user:
  name: 白云苍狗
  first_name: 苍狗
  last_name: 白云
  email: admin@imalun.com
  domain: https://www.imalun.com
  avatar: https://www.imalun.com/images/avatar.jpg
  describe: 醒，亦在人间；梦，亦在人间。
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。<br/><br/>提醒：评论插件已移除，申请可以点左侧联系我
  copyrightYear: 2019
  birthDay: 11/19/2019 17:00:00 #计时开始时间

# 图标
favicon:
  logo: favicon-32x32.png
  icon16: favicon-16x16.png 
  icon32: favicon-32x32.png
  appleTouchIcon: apple-touch-icon.png
  webmanifest: /site.webmanifest
  visibilitychange: true

# 头部菜单
top_bars:
  - title: 首页
    url: /
  - title: 归档
    url: /archives/
  - title: 友链
    url: /links/
  #- title: 树洞
  #  url: /comment/
  - title: 玩具
    url: /project/
  - title: 关于
    url: /about/
  - title: 虫洞
    url: https://foreverblog.cn/go.html
    noswup: true
    target: _blank

# 横幅配置
banner:
  index:
    type: video
    bgurl: //cdn.moji.com/websrc/video/autumn20190924.mp4
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!

# 侧栏
sidebar:
  typedTextPrefix: I`m
  typedText: [ 'Web Developer' ]
  info: 
    - key: sidebar.residence
      val: Mars
    - key: sidebar.city
      val: WuHan
    - key: sidebar.age
      val: 18
  social:
    - icon: fab fa-github
      url: https://github.com/MaLuns
      name: Github
    - icon: fab fa-github-alt
      url: https://gitee.com/ml13
      name: Gitee
    - icon: fab fa-weibo
      url: https://weibo.com/u/5022481764
      name: Weibo
    - icon: fas fa-rss
      url: atom.xml
      name: Rss
      
# 关于页
about:
  title: 一觉游仙好梦，任它竹冷松寒。轩辕事，古今谈，风流河山。沉醉负白首，舒怀成大观。醒，亦在人间；梦，亦在人间。
  introduction: 大家好，我是<strong>白云苍狗</strong>，很高兴您能在浩瀚如烟的互联网世界里发现这个博客，更感谢您能够饶有兴致地浏览这个页面。建立这个 Blog 是出于兴趣爱好，我将在此分会分享一些学习笔记，可能还会分享少许图片、视频以及其他有趣东西的链接。
  blog: 
    <ul class="trm-list">
      <li>程序：Hexo </li>
      <li>主题：<a href="https://github.com/MaLuns/hexo-theme-async" style="font-weight:bold;" target="_blank" rel="nofollow">Hexo-theme-async<a/> </li>
      <li>托管：<a href="https://github.com/MaLuns/blog" style="font-weight:bold;" target="_blank" rel="nofollow">Github<a/> </li>
      <li>图床：Tencent CloudBase </li>
      <li>评论：Tencent CloudBase </li>
    </ul>
  privacy: 
    本网站不会追踪访客行为，且不要求访客提供任何敏感信息（比如真实姓名、身份证号码、手机号等），因而也不存在任何隐私泄漏问题。访客参与评论，必须遵守法律法规和基本道德规范，文明礼貌。严禁发布任何有关淫秽、反动、暴力、博彩、恐吓、低俗的内容或违法信息，在尊重言论自由的同时请保持和平与理性。请勿对他人采取不友好的评论或其它过激行为。
    <br/><br/>
    本博客采用 <strong><a class="trm-label" href="https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh">知识产权署名-非商业性使用 4.0 国际许可协议</a></strong> 进行许可。
    <br/>
    转载前请联系作者获得许可，并注明原文链接。如有侵权，请留言告知，我会一周内删除。谢谢！
    
# 开启 Service Worker
sw: true

# rss 地址
rss: atom.xml

# 网页访问统计
webAnalytics:  
  enable: true 
  baidu: bbad9d8e1fd8e044d365c2ce0d114c73

# 评论插件
comment:
  enable: false
  bComments:
    v: 0.0.12
    env: h-17b316