post_wordcount:
  item_text: true
  wordcount: true         # 单篇 字数统计
  min2read: true          # 单篇 阅读时长
  totalcount: false       # 网站 字数统计
  separated_meta: true

version: 0.0.1

highlight_theme: normal

favicon:
  visibilitychange: true
  narmal: /images/favicon.ico
  hidden: /images/failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

headerbg: 
    #- '/images/header-leg.jpg'
    #- 'http://www.pilicn.com/wp-content/themes/pili/images/n-bg3.png'
    - 'http://www.pilicn.com/wp-content/themes/pili/images/n-bg00.jpg'
    - 'http://www.pilicn.com/wp-content/themes/pili/images/g-bg12.jpg'
  
menu:
  home: /
  category: /categories
  links: /links
  about: //mablog.coding.me/cv/
  github: //github.com/MaLuns
  bilibili: //space.bilibili.com/12763040
  qq: tencent://message/?uin=384399021&amp;Site=有事Q我&amp;Menu=yes

user:
  avatar: images/avatar.jpg
  desc:  醒，亦在人间；梦，亦在人间

rss: atom.xml