post_wordcount:
  item_text: true
  wordcount: true         # 单篇 字数统计
  min2read: true          # 单篇 阅读时长
  totalcount: false       # 网站 字数统计
  separated_meta: true

version: 0.0.2

highlight_theme: normal

favicon:
  visibilitychange: true
  narmal: /images/favicon.ico
  hidden: /images/failure.ico
  show_text: (/≧▽≦/)咦！又好了！
  hide_text: (●—●)喔哟，崩溃啦！
  apple_touch_icon: /images/apple-touch-icon-next.png
  safari_pinned_tab: /images/logo.svg

headerbg: 
    #- '/images/header-leg.jpg'
    #- 'http://www.pilicn.com/wp-content/themes/pili/images/n-bg3.png'
    - '/images/n-bg00.jpg'
    - '/images/g-bg12.jpg'
  
menu:
  category: /categories
  links: /links
  about: //mablog.coding.me/cv/
  github: //github.com/MaLuns
  bilibili: //space.bilibili.com/12763040
  qq: tencent://message/?uin=384399021&amp;Site=有事Q我&amp;Menu=yes

user:
  avatar: images/avatar.jpg
  desc:  醒，亦在人间；梦，亦在人间

rss: atom.xml

# 
comment: true

# gitalk
gitalk:
  createIssueManually: true
  owner: MaLuns
  repo: MalBlog
  clientID: b971d416833059d04dc7
  clientSecret: 92cacb8f281b908089f86701b66cc9afa11772db

# 友联
links:
  - name: hexo
    url: https://hexo.io/
    image: https://d33wubrfki0l68.cloudfront.net/6657ba50e702d84afb32fe846bed54fba1a77add/827ae/logo.svg
    desc: 快速、简洁且高效的博客框架
  - name: 随心
    url: https://uiluil.com/
    image: https://uiluil.com/medias/logo.png
    desc: 从来没有真正的绝境, 只有心灵的迷途
  - name: 白云苍狗
    url: https://www.imalun.com/
    image: https://www.imalun.com/images/avatar.jpg
    desc: 醒，亦在人间；梦，亦在人间

