import './component/com-button'
import './component/com-switch'
import './component/com-slider'
import './component/com-color-picker'
import './component/com-tips'
import './component/com-radio'
import './component/com-icon'
import './component/com-checkbox'
import ComMessage from './component/com-message'
import './component/comment/src/index'
window.ComMessage = ComMessage;

import './app'
import './cursor-effects'
import './aplayer'
import './title'